apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landing-app
  template:
    metadata:
      labels:
        app: landing-app
    spec:
      containers:
        - name: landing-app
          image: ghcr.io/thewasta/click2eat-landing:example
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: landing-service
spec:
  selector:
    app: landing-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
