name: Deploy kubernetes
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@master
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{github.actor}}
         password: ${{secrets.GITHUB_TOKEN}}
      - name: Build image
        run: |
          docker build . --tag ghcr.io/thewasta/click2eat-landing:$(echo $GITHUB_SHA | head -c7) .
          docker push ghcr.io/thewasta/click2eat-landing:$(echo $GITHUB_SHA | head -c7) .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}