name: Deploy kubernetes
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out
        uses: actions/checkout@master
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{github.actor}}
         password: ${{secrets.GITHUB_TOKEN}}
      - name: Build image
        run: |
          docker build --tag ghcr.io/thewasta/click2eat-landing:$(echo $GITHUB_SHA | head -c7) .
          docker push ghcr.io/thewasta/click2eat-landing:$(echo $GITHUB_SHA | head -c7)
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|ghcr.io/thewasta/click2eat-landing:.*|ghcr.io/thewasta/click2eat-landing:'${TAG}'|' $GITHUB_WORKSPACE/deployment.digitalocean.yaml
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}
      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/deployment.digitalocean.yaml
      - name: Verify deployment
        run: kubectl rollout status deployment/landing-app