name: Deploy kubernetes
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
    tags-ignore:
      - '**'
  workflow_dispatch:
jobs:
  #  build:
  #    runs-on: ubuntu-latest
  #    permissions:
  #      contents: read
  #      packages: write
  #    steps:
  #      - name: Check out
  #        uses: actions/checkout@master
  #      - name: 'Login to GitHub Container Registry'
  #        uses: docker/login-action@v1
  #        with:
  #         registry: ghcr.io
  #         username: ${{github.actor}}
  #         password: ${{secrets.GITHUB_TOKEN}}
  #      - name: Install doctl
  #        uses: digitalocean/action-doctl@v2
  #        with:
  #          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  #      - name: Build image
  #        run: |
  #          docker build --tag ghcr.io/thewasta/click2eat-landing:$(echo $GITHUB_SHA | head -c7) .
  #          docker push ghcr.io/thewasta/click2eat-landing:$(echo $GITHUB_SHA | head -c7)
#  notification_start:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Notify start action
#        uses: rjstone/discord-webhook-notify@v1
#        with:
#          severity: info
#          color: '#0059ff'
#          details: New push to landing website
#          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  deploy_pro:
    name: Deploy production
#    if: github.ref == 'ref/heads/main'
#    needs:
#      - notification_start
    runs-on: [self-hosted, prod]
    environment: pro
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Reload application
        run: pm2 reload landing
#      - name: Reload application
#        run: pm2 reload 1
#      - name: Deploy Success
#        uses: rjstone/discord-webhook-notify@v1
#        if: success()
#        with:
#          severity: info
#          details: Desplegado producción con éxito!
#          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
#      - name: Deploy failed
#        uses: rjstone/discord-webhook-notify@v1
#        if: failure()
#        with:
#          severity: error
#          details: Ha fallado el despliegue a producción
#          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}